CREATE TABLE ITEM (
	I_ID	NOT NULL,
	weight	DECIMAL,
	volume 	DECIMAL,
	lat		DECIMAL NOT NULL,	
	lon		DECIMAL NOT NULL,
	req_num INTEGER,
	ID		INTEGER NOT NULL,
	PRIMARY KEY (I_ID),
	FOREIGN KEY (lat) REFERENCES WAREHOUSE(lat)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	FOREIGN KEY (lon) REFERENCES WAREHOUSE(lon)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	FOREIGN KEY(ID) REFERENCES COMPANY(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
